defaults: &defaults
  host: localhost
  port: 27017
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: locomotive_dev

test:
  <<: *defaults
  database: locomotive_test

# set these environment variables on your prod server
production:
   <<: *defaults
   database: locomotive_prod

  # other settings for production
  # host: 
  # port: 
  # username: 
  # password:
  # database:

  # heroku
  # uri:

  # bushido (mongohq_url will also work)
